twitter_username: DouglasKGAraujo
github_username:  dkgaraujo
toc: true
default_badges:
  colab: true
google_search: 8e62117eaaea69e2e
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

sidebars: [home_sidebar]
baseurl: /
plugins:
    - jekyll-remote-theme
    
remote_theme: fastai/nbdev-jekyll-theme