# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"augm_with_sdmx": "00_augmentation.ipynb"}

modules = ["augmentation.py"]

doc_url = "https://dkgaraujo.github.io/gingado/"

git_url = "https://github.com/dkgaraujo/gingado/tree/main/"

def custom_doc_links(name): return None
