# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"AugmentSDMX": "00_augmentation.ipynb",
         "ggdBenchmark": "00_benchmark.ipynb",
         "ClassificationBenchmark": "00_benchmark.ipynb",
         "RegressionBenchmark": "00_benchmark.ipynb",
         "load_BarroLee_1994": "00_datasets.ipynb",
         "make_causal_effect": "00_datasets.ipynb",
         "ggdModelDocumentation": "00_documentation.ipynb",
         "ModelCard": "00_documentation.ipynb",
         "get_datetime": "00_utils.ipynb",
         "Lag": "00_utils.ipynb",
         "list_SDMX_sources": "00_utils.ipynb",
         "list_all_dataflows": "00_utils.ipynb",
         "load_SDMX_data": "00_utils.ipynb",
         "load_EURFX_data": "00_utils.ipynb"}

modules = ["augmentation.py",
           "benchmark.py",
           "datasets.py",
           "model_documentation.py",
           "utils.py"]

doc_url = "https://dkgaraujo.github.io/gingado/"

git_url = "https://github.com/dkgaraujo/gingado/tree/main/"

def custom_doc_links(name): return None
