# AUTOGENERATED! DO NOT EDIT! File to edit: 02_documentation.ipynb (unless otherwise specified).

__all__ = ['ModelCard']

# Cell
#export
from .utils import get_username, get_datetime

# Cell
class ModelCard:
    def __init__(self, from_template: bool = True):
        if from_template:
            self.start_from_template()

    def start_from_template(self):
        """Creates an empty model card template, then fills it with information that is automatically obtained from the system"""

        self.model_details = {}
        self.model_details['developer'] = get_username()
        self.model_details['datetime'] = get_datetime()
        self.model_details['version'] = "1"
        self.model_details['task'] = None
        self.model_details['framework'] = None
        self.model_details['architecture'] = None
        self.model_details['parameters'] = None
        self.model_details['optimizer'] = None
        self.model_details['type'] = None
        self.model_details['info'] = None
        self.model_details['citation'] = None
        self.model_details['license'] = None
        self.model_details['contact'] = None

        self.intended_use = {}
        self.intended_use['primary_uses'] = None
        self.intended_use['primary_users'] = None
        self.intended_use['out_of_scope'] = None

        self.factors = {}
        self.factors['relevant'] = None
        self.factors['evaluation'] = None

        self.metrics = {}
        self.metrics['performance_measures'] = None
        self.metrics['thresholds'] = None
        self.metrics['variation_approaches'] = None

        self.data = {}
        self.data['datasets'] = None
        self.data['preprocessing'] = None
        self.data['motivation'] = None

        self.ethical_cons = {}
        self.ethical_cons['impact'] = None
        self.ethical_cons['risks'] = None
        self.ethical_cons['mitigation'] = None
        self.ethical_cons['avoid'] = None

        self.caveats_recomm = {}
        self.caveats_recomm['caveats'] = None
        self.caveats_recomm['recommendations'] = None
        self.caveats_recomm['misc_notes'] = None

        return self

    def __setitem__(self, key, value):
        setattr(self, key, value)

    def __getitem__(self, key):
        return getattr(self, key)