project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue, edit]
  navbar:
    background: primary
    search: false
  sidebar:
    style: docked
    search: true

metadata-files: [nbdev.yml, sidebar.yml]

bibliography: gingado.bib